dataset: allenai/real-toxicity-prompts
output_file: toxic_suffixes_l8b.jsonl
model_name: meta-llama/Meta-Llama-3.1-8B
num_suffixes: 2000
seed: 42
save_golden_prefix: true
toxicity_threshold: 0.7
max_tokens: 64
min_tokens: 15
# Nested keys to access the text and toxicity score in the dataset.
text_keys: ["continuation", "text"]
toxicity_keys: ["continuation", "toxicity"]